package edu.kirkwood.controller;

import edu.kirkwood.model.Depreciation;
import edu.kirkwood.model.Fraction;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the Depreciation model class.
 * Tests the core depreciation calculation logic using Arrange-Act-Assert pattern.
 */
class DepreciationCalculatorTest {

    @Test
    void testValidDepreciationCreation() {
        // Arrange
        int assetCost = 100000;
        int salvageValue = 10000;
        int usefulLife = 5;

        // Act
        Depreciation depreciation = new Depreciation(assetCost, salvageValue, usefulLife);

        // Assert
        assertNotNull(depreciation);
        assertEquals(assetCost, depreciation.getAssetCost().getNumerator());
        assertEquals(salvageValue, depreciation.getSalvageValue().getNumerator());
        assertEquals(usefulLife, depreciation.getUsefulLife());
    }

    @Test
    void testDepreciationWithEqualSalvageAndCost() {
        // Arrange
        int assetCost = 50000;
        int salvageValue = 50000;
        int usefulLife = 5;

        // Act
        Depreciation depreciation = new Depreciation(assetCost, salvageValue, usefulLife);

        // Assert
        assertNotNull(depreciation);
        Fraction annualDepreciation = depreciation.calculateAnnualDepreciation();
        assertEquals(0, annualDepreciation.getNumerator());
    }

    @Test
    void testNegativeAssetCostThrowsException() {
        // Arrange
        int assetCost = -100000;
        int salvageValue = 10000;
        int usefulLife = 5;

        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> {
            new Depreciation(assetCost, salvageValue, usefulLife);
        });
    }

    @Test
    void testSalvageValueGreaterThanAssetCostThrowsException() {
        // Arrange
        int assetCost = 50000;
        int salvageValue = 60000;
        int usefulLife = 5;

        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> {
            new Depreciation(assetCost, salvageValue, usefulLife);
        });
    }

    @Test
    void testZeroUsefulLifeThrowsException() {
        // Arrange
        int assetCost = 100000;
        int salvageValue = 10000;
        int usefulLife = 0;

        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> {
            new Depreciation(assetCost, salvageValue, usefulLife);
        });
    }

    /**
     * These code below were generated by claude Ai
     */
    @Test
    void testAnnualDepreciationCalculation() {
        // Arrange
        int assetCost = 100000;
        int salvageValue = 10000;
        int usefulLife = 5;
        Depreciation depreciation = new Depreciation(assetCost, salvageValue, usefulLife);
        int expectedAnnualDepreciation = (assetCost - salvageValue) / usefulLife; // 18000

        // Act
        Fraction annualDepreciation = depreciation.calculateAnnualDepreciation();

        // Assert
        assertEquals(expectedAnnualDepreciation, annualDepreciation.getNumerator());
        assertEquals(1, annualDepreciation.getDenominator());
    }

    @Test
    void testAccumulatedDepreciationAtYearZero() {
        // Arrange
        int assetCost = 100000;
        int salvageValue = 10000;
        int usefulLife = 5;
        Depreciation depreciation = new Depreciation(assetCost, salvageValue, usefulLife);

        // Act
        Fraction accumulatedDepreciation = depreciation.calculateAccumulatedDepreciation(0);

        // Assert
        assertEquals(0, accumulatedDepreciation.getNumerator());
    }

    @Test
    void testAccumulatedDepreciationAtEndOfLife() {
        // Arrange
        int assetCost = 100000;
        int salvageValue = 10000;
        int usefulLife = 5;
        Depreciation depreciation = new Depreciation(assetCost, salvageValue, usefulLife);
        int expectedAccumulated = assetCost - salvageValue; // 90000

        // Act
        Fraction accumulatedDepreciation = depreciation.calculateAccumulatedDepreciation(usefulLife);

        // Assert
        assertEquals(expectedAccumulated, accumulatedDepreciation.getNumerator());
    }

    @Test
    void testItemValueAtYearZero() {
        // Arrange
        int assetCost = 100000;
        int salvageValue = 10000;
        int usefulLife = 5;
        Depreciation depreciation = new Depreciation(assetCost, salvageValue, usefulLife);

        // Act
        Fraction itemValue = depreciation.calculateItemValue(0);

        // Assert
        assertEquals(assetCost, itemValue.getNumerator());
    }

    @Test
    void testItemValueAtEndOfLifeEqualsSalvageValue() {
        // Arrange
        int assetCost = 100000;
        int salvageValue = 10000;
        int usefulLife = 5;
        Depreciation depreciation = new Depreciation(assetCost, salvageValue, usefulLife);

        // Act
        Fraction itemValue = depreciation.calculateItemValue(usefulLife);

        // Assert
        assertEquals(salvageValue, itemValue.getNumerator());
        assertEquals(1, itemValue.getDenominator());
    }
}